# theme url: https://github.com/panr/hugo-theme-hello-friend
# google search guide: https://support.google.com/webmasters/answer/9274190

baseurl: 'https://arcticnoah.consulting'
title: arcticnoah | Site
languageCode: en-us
theme:
  - hugo-video
  - hello-friend
paginate: 5

# Uncomment below to add 'Disqus' section to blog posts
# disqusShortname: "arcticnoah"

params:
  # dir name of your blog content (default is `content/posts`)
  contentTypeName: posts

  # "light" or "dark"
  defaultTheme: light

  # if you set this to 0, only submenu trigger will be visible
  showMenuItems: 4

  # Show reading time in minutes for posts
  showReadingTime: false

taxonomies:
  tag: tags
  category: categories
  focus: focus

languages:
  en:
    title: arcticnoah
    subtitle: ''
    keywords: ''
    copyright: ''
    menuMore: Show more
    writtenBy: Written by
    readMore: Read more
    readOtherPosts: Read other posts
    newerPosts: Newer posts
    olderPosts: Older posts
    minuteReadingTime: min read
    dateFormatSingle: '2006-01-02'
    dateFormatList: '2006-01-02'
    # leave empty to disable, enter display text to enable
    lastModDisplay: 'Last Modified:'

    params:
      logo:
        logoText: arcticnoah
        logoHomeLink: /
        # or
        #
        # path = "/img/your-example-logo.svg"
        # alt = "Your example logo alt text"
    
    # TODO: make the order of this be the same in the menu of the site
    menu:
      main:
        - identifier: about
          name: About
          url: /
        - identifier: blog
          name: Blog
          url: /blog
        - identifier: dailylog
          name: Daily Log
          url: /dailylog
        - identifier: portfolio
          name: Portfolio
          url: /portfolio
