[context.production.environment]
  HUGO_VERSION = "0.82.1"

[context.branch-deploy.environment]
  HUGO_VERSION = "0.82.1"
  
[context.deploy-preview.environment]
  HUGO_VERSION = "0.82.1"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "frame-ancestors https://www.youtube-nocookie.com"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"